### ISSUE TITLE
Relaxed validation for empty AttributeStatement in AuthnResponse

### ISSUE THREAD

**Issue by albinsunnanbo** [KentorIT/authservices#185]
Saml2Responses with empty AttributeStatement

    <saml2:AttributeStatement/> 

are not allowed according to the standard. They should either contain other elements or be non existing all together. AuthServices throws an exception

	Exception information: 
		Exception type: XmlException 
		Exception message: ID3061: The given element ('AttributeStatement','urn:oasis:names:tc:SAML:2.0:assertion') is empty.
	   at System.IdentityModel.Tokens.Saml2SecurityTokenHandler.ReadAttributeStatement(XmlReader reader)
	   at System.IdentityModel.Tokens.Saml2SecurityTokenHandler.ReadAssertion(XmlReader reader)
	   at System.IdentityModel.Tokens.Saml2SecurityTokenHandler.ReadToken(XmlReader reader)
	   at Kentor.AuthServices.Saml2P.Saml2Response.<CreateClaims>d__5.MoveNext()
	   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
	   at Kentor.AuthServices.Saml2P.Saml2Response.GetClaims(ISPOptions options)
	   at Kentor.AuthServices.WebSso.AcsCommand.ProcessResponse(IOptions options, Saml2Response samlResponse)
	   at Kentor.AuthServices.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options)

However if you don't use any attributes I would prefer a relaxed validation (configurable) that allows messages from a non conformant IDP to be processed.

**Comment by AndersAbel** [comment]
Lax validation is a tricky issue, especially for security sensitive applications. As long as possible, I'd like to keep AuthServices strict with the standard. 

In this case, it is even more complex as the exception is thrown by the .NET framework code and not from AuthServices which probably means quite a lot of work to allow lax handling.

Is it really needed? Unless not, I'd prefer to close this issue as won't fix.

**Comment by albinsunnanbo** [comment]
I see, it would require some ugly patch up of the XML message before using the .NET validation.
For daily use it's not an issue, however our IDP sometimes sends invalid SAML2-data with an empty AttributeStatement tag. If the problem does not escalate it is highly desired, but not absolutely needed from our application point of view.

I agree that the default behavior of AuthServices should be strict to the standard, any deviations should be explicitly configured in your application.

I close the issue for now.
