### ISSUE TITLE
Metadata download - multiple signing keys (key rollover)

### ISSUE THREAD

**Issue by doormalena** [KentorIT/authservices#190]
Hi!

With 0.12.0 (and below) the following exception occurs when the IDP does a rollover of the signing certificate and the SP (Kentor) is configured to auto-download the metadata at startup. During a rollover there are two signing certificates for a period of time available in the metadata. Depending on where we are in time within this period, either the first or the second is valid. The IDP product we use is ADFS 2012R2.

If you want I can send you a fix for this. I have changed Saml2Response and IdentityProvider classes to support multiple signing certificates.

-------------------

Sequence contains more than one element 		
			at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Kentor.AuthServices.IdentityProvider.ReadMetadataIdpDescriptor(ExtendedEntityDescriptor metadata) in d:\Data\Workspaces\doormalena\authservices-0.12.0\Kentor.AuthServices\IdentityProvider.cs:line 328
   at Kentor.AuthServices.IdentityProvider.ReadMetadata(ExtendedEntityDescriptor metadata) in d:\Data\Workspaces\doormalena\authservices-0.12.0\Kentor.AuthServices\IdentityProvider.cs:line 307
   at Kentor.AuthServices.IdentityProvider.DoLoadMetadata() in d:\Data\Workspaces\doormalena\authservices-0.12.0\Kentor.AuthServices\IdentityProvider.cs:line 275
   at Kentor.AuthServices.IdentityProvider.set_LoadMetadata(Boolean value) in d:\Data\Workspaces\doormalena\authservices-0.12.0\Kentor.AuthServices\IdentityProvider.cs:line 108
   at Kentor.AuthServices.IdentityProvider..ctor(IdentityProviderElement config, ISPOptions spOptions) in d:\Data\Workspaces\doormalena\authservices-0.12.0\Kentor.AuthServices\IdentityProvider.cs:line 46
   at Kentor.AuthServices.Configuration.IdentityProviderCollection.RegisterIdentityProviders(IOptions options) in d:\Data\Workspaces\doormalena\authservices-0.12.0\Kentor.AuthServices\Configuration\IdentityProviderCollection.cs:line 58
   at Kentor.AuthServices.Configuration.Options.get_FromConfiguration() in d:\Data\Workspaces\doormalena\authservices-0.12.0\Kentor.AuthServices\Configuration\Options.cs:line 25
   at Kentor.AuthServices.Mvc.AuthServicesController.get_Options()
   at Kentor.AuthServices.Mvc.AuthServicesController.SignIn()
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.ActionInvocation.InvokeSynchronousActionMethod()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](IAsyncResult asyncResult, Object tag)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](IAsyncResult asyncResult, Object tag)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

**Comment by AndersAbel** [comment]
Support for key rollover is highly desired.

If you have a solution for it, a pull request is appreciated.

There is already an issue #105 on it, so I'm closing this one as a duplicate.
