### ISSUE TITLE
Kentor integrate with OKTA but not work on window server

### ISSUE THREAD

**Issue by tung1401** [KentorIT/authservices#384]
I almost finish implement Kentor integrate with OKTA, but I have a problem when deploy to my window server.

I got the error like this when I open the log error on my Database

	MachineName: DATCHI-TS02, TimeStamp: 1/17/2016 5:13:11 AM, User: , Controller: AuthServices, Message: Object reference not set to an instance of an object., Source:    at Kentor.AuthServices.Mvc.CommandResultExtensions.SignInSessionAuthenticationModule(CommandResult commandResult)
	   at Kentor.AuthServices.Mvc.AuthServicesController.Acs()
	   at lambda_method(Closure , ControllerBase , Object[] )
	   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
	   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
	   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
	   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
	   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
	   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
	   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
	   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
	   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) 

and got another error about 
POST Acs 500 Internal Server Error
When open firebug in firefox

Have anyone know about this issue, please suggest me.

Thank you

**Comment by albinsunnanbo** [comment]
Can you checkout the source (with the tag corresponding to your version), build and upload the PDB files to get line numbers in the error message?
Or could you attach a debugger and debug the code?

The only thing that looks like it could be null would be `FederatedAuthentication.SessionAuthenticationModule` in `CommandResultHttpExtension.SignInSessionAuthenticationModule`. Have you configured the SessionAuthenticationModule properly in your web.config?

**Comment by AndersAbel** [comment]
As  @albinsunnanbo suggest this looks like you haven't loaded the session authentication module in your web.config. See https://github.com/KentorIT/authservices/blob/master/doc/Configuration.md#loading-modules. You only need to add the line for the session authentication module.

**Comment by albinsunnanbo** [comment]
I can confirm that omitting the SessionAuthenticationModule configuration produces this error.
I created a pull request #385 to make the error message more helpful in future versions.

**Comment by tung1401** [comment]
Is it correct web.config ?
<system.webServer>
 <modules runAllManagedModulesForAllRequests="true">
      <add name="SessionAuthenticationModule" type="System.IdentityModel.Services.SessionAuthenticationModule, System.IdentityModel.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" preCondition="managedHandler" />
      <add name="Saml2AuthenticationModule" type="Kentor.AuthServices.HttpModule.Saml2AuthenticationModule, Kentor.AuthServices.HttpModule"/>
	</modules>
</system.webServer>

**Comment by AndersAbel** [comment]
No, when using the MVC lib you should only have the line for the SessionAuthenticationModule. Remove the Saml2AuthenticationModule.

**Comment by tung1401** [comment]
Thank you, I remove it  but not work. still error  at Kentor.AuthServices.Mvc.CommandResultExtensions.SignInSessionAuthenticationModule(CommandResult commandResult)


public ActionResult Acs()
        {
            var result = CommandFactory.GetCommand(CommandFactory.AcsCommandName).Run(
                Request.ToHttpRequestData(),
                Options);

            result.SignInSessionAuthenticationModule();
            return result.ToActionResult();
        }

I think RESULT is null, so SignInSessionAuthenticationModule() return exception. Where I should do checking?

Regards

**Comment by AndersAbel** [comment]
Result should never be null. If it was, you would get an ArgumentNullException. It looks like you haven't successfully loaded the SessionAuthenticationModule. Please update your nuget packages to 0.15.0 that I released yesterday. That version will give you a better exception message.

What web server are you running this on? Putting the modules under system.webServer is for modern IIS. On older IIS and on the Cassini development server for visual studio the modules should be put under system.web.
