### ISSUE TITLE
LoadMetadata from local file fails if root element is `<EntityDescriptor>`

### ISSUE THREAD

**Issue by Thaoden** [KentorIT/authservices#533]
To check this, I manually edited the file `Kentor.AuthServices.Tests.Metadata.SingleIdpInEntitiesDescriptor.xml` so that the root element is `<EntityDescriptor>`. I then ran the test suite, three tests failed; I got the following error message and stack trace:

> Test Name:	MetadataLoader_LoadIdentityProvider_UnpacksEntitiesDescriptorIfFlagSet
Test FullName:	Kentor.AuthServices.Tests.Metadata.MetadataLoaderTests.MetadataLoader_LoadIdentityProvider_UnpacksEntitiesDescriptorIfFlagSet
Test Source:	E:\Visual Studio Projects _ old\authservices-aspnetcore\Kentor.AuthServices.Tests\Metadata\MetadataLoaderTests.cs : line 83
Test Outcome:	Failed
Test Duration:	0:00:00,0068432

> Result StackTrace:	
at System.IdentityModel.Metadata.MetadataSerializer.ReadMetadataCore(XmlReader reader, SecurityTokenResolver tokenResolver)
   at System.IdentityModel.Metadata.MetadataSerializer.ReadMetadata(XmlReader reader, SecurityTokenResolver tokenResolver)
   at System.IdentityModel.Metadata.MetadataSerializer.ReadMetadata(XmlReader reader)
   at Kentor.AuthServices.Metadata.MetadataLoader.Load(Stream metadataStream) in E:\Visual Studio Projects _ old\authservices-aspnetcore\Kentor.AuthServices\Metadata\MetadataLoader.cs:line 103
   at Kentor.AuthServices.Metadata.MetadataLoader.Load(String metadataLocation) in E:\Visual Studio Projects _ old\authservices-aspnetcore\Kentor.AuthServices\Metadata\MetadataLoader.cs:line 89
   at Kentor.AuthServices.Metadata.MetadataLoader.LoadIdp(String metadataLocation, Boolean unpackEntitiesDescriptor) in E:\Visual Studio Projects _ old\authservices-aspnetcore\Kentor.AuthServices\Metadata\MetadataLoader.cs:line 58
   at Kentor.AuthServices.Tests.Metadata.MetadataLoaderTests.MetadataLoader_LoadIdentityProvider_UnpacksEntitiesDescriptorIfFlagSet() in E:\Visual Studio Projects _ old\authservices-aspnetcore\Kentor.AuthServices.Tests\Metadata\MetadataLoaderTests.cs:line 86
Result Message:	
Test method Kentor.AuthServices.Tests.Metadata.MetadataLoaderTests.MetadataLoader_LoadIdentityProvider_UnpacksEntitiesDescriptorIfFlagSet threw exception: 
System.IdentityModel.Metadata.MetadataSerializationException: ID3260: The root element of a metadata document must be either an EntityDescriptor or an EntitiesDescriptor.

According to the error message, a root element of `<EntityDescriptor>` should not throw an exception.

**Comment by AndersAbel** [comment]
Did you remember to move the namespace declaration `xmlns="urn:oasis:names:tc:SAML:2.0:metadata"` when you edited the file?

**Comment by Thaoden** [comment]
I think I forgot that. But then the error message is quite misleading.

**Comment by AndersAbel** [comment]
Yes it is misleading when the namespace is missing, but the exception is from within the .NET framework so it's nothing that is simple to fix.
