### ISSUE TITLE
Package .21 Kentor LogoutCommand throwing unhandled null reference exceptions

### ISSUE THREAD

**Issue by Coderrob** [KentorIT/authservices#682]
```
2017-04-05 18:31:22.5610,Kentor.AuthServices.Owin.KentorAuthServicesAuthenticationMiddleware,"Expanded AuthServicesUrl
  AssertionConsumerServiceUrl: http://localhost:13070/AuthServices/Acs
  SignInUrl: http://localhost:13070/AuthServices/SignIn
  LogoutUrl: http://localhost:13070/AuthServices/Logout
  ApplicationUrl: http://localhost:13070/",
2017-04-05 18:31:22.5610,HTTP Logging,HTTP Response Exception,"System.InvalidOperationException ---> System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Kentor.AuthServices.WebSso.LogoutCommand.InitiateLogout(HttpRequestData request, Uri returnUrl, IOptions options)
   at Kentor.AuthServices.WebSso.LogoutCommand.Run(HttpRequestData request, String returnPath, IOptions options)
   at Kentor.AuthServices.Owin.KentorAuthServicesAuthenticationHandler.<ApplyResponseGrantAsync>d__3.MoveNext()
```

Found it was a missing null check in a logging call where idp?.SingleLogoutServiceUrl.OriginalString wasn't being checked for null.

```
            options.SPOptions.Logger.WriteVerbose("Initiating logout, checking requirements for federated logout"
                + "\n  Issuer of LogoutNameIdentifier claim (should be Idp entity id): " + idpEntityId
                + "\n  Issuer is a known Idp: " + knownIdp
                + "\n  Session index claim (should have a value): " + sessionIndexClaim
                + "\n  Idp has SingleLogoutServiceUrl: " + idp?.SingleLogoutServiceUrl.OriginalString
                + "\n  There is a signingCertificate in SPOptions: " + (options.SPOptions.SigningServiceCertificate != null)
                + "\n  Idp configured to DisableOutboundLogoutRequests (should be false): " + idp?.DisableOutboundLogoutRequests);
```

Looks like it was fixed a few hours ago but package .21 is broken for us. Package .20 is broken for us. We're stuck at .19.

**Comment by AndersAbel** [comment]
I'll try to get a 0.21.1 out tomorrow with the fix I implemented today. This totally tripped me. Found out that the unit tests were broken (and had been for a while) too without the code coverage catching it.

**Comment by Coderrob** [comment]
Sweet, glad to hear! 

I went to push a PR today from a clone of master yesterday, but my merge showed it was already fixed by this morning. Had me scratching my head. Either way looks like you're on top of it. 👍
