### ISSUE TITLE
KeyNotFoundException when looking up IdP in IdentityProviderDictionary

### ISSUE THREAD

**Issue by anthonyrstevens** [KentorIT/authservices#743]
Hi, I'm using Kentor.AuthServices.Owin in an ASP.NET MVC 5 app and I'm seeing the following exception when presented with an IdP-initiated assertion:

```
System.Collections.Generic.KeyNotFoundException: No Idp with entity id "http://idp.oktadev.com" found. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary``2.get_Item(TKey key)
   at Kentor.AuthServices.Configuration.IdentityProviderDictionary.get_Item(EntityId entityId)
   --- End of inner exception stack trace ---
   at Kentor.AuthServices.Configuration.IdentityProviderDictionary.get_Item(EntityId entityId)
   at Kentor.AuthServices.Saml2P.Saml2Response.CheckIfUnsolicitedIsAllowed(IOptions options)
   at Kentor.AuthServices.Saml2P.Saml2Response.<CreateClaims>d__57.MoveNext()
   at System.Collections.Generic.List``1..ctor(IEnumerable``1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable``1 source)
   at Kentor.AuthServices.Saml2P.Saml2Response.GetClaims(IOptions options)
   at Kentor.AuthServices.WebSso.AcsCommand.ProcessResponse(IOptions options, Saml2Response samlResponse, StoredRequestState storedRequestState)
   at Kentor.AuthServices.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options)
   at Kentor.AuthServices.Owin.KentorAuthServicesAuthenticationHandler.<AuthenticateCoreAsync>d__0.MoveNext()
```

This appears to be a similar error to issue #477, but there is a <saml:Issuer> element in the incoming assertion, so it's not the same cause.

This same error occurs with two different, unrelated SAML IdP sources. The Kentor Stub IdP works, however. I'm guessing it has something to do with my IdentityProvider configuration. Relevant bits:

```
public void ConfigureAuth(IAppBuilder app) {
...
// vm is an object containing SAML configuration parameters
var spOptions = CreateSpOptions(app, vm);

var authServicesOptions = new KentorAuthServicesAuthenticationOptions(false)
{
	SPOptions = spOptions,
	AuthenticationType = vm.OwinProviderType,
	AuthenticationMode = AuthenticationMode.Passive,
	Caption = vm.Caption,
	SignInAsAuthenticationType = "ExternalCookie",
};

var allowIdpInitiatedSso = vm.HasFeature(Saml2IntegrationFeature.AllowIdpInitiatedSso);
var idp = new IdentityProvider(new EntityId(vm.IdpEntityId), spOptions)
{
	AllowUnsolicitedAuthnResponse = allowIdpInitiatedSso,
	Binding = Saml2BindingType.HttpRedirect,
	SingleSignOnServiceUrl = new Uri(vm.IdpSignOnUrl),
};

var cert = CertificateUtils.ConstructX509Certificate2(vm.IdpCertificateContents);
idp.SigningKeys.AddConfiguredKey(cert);

authServicesOptions.IdentityProviders.Add(idp);
...
} // ConfigureAuth
```

Any help is appreciated.

**Comment by AndersAbel** [comment]
Your configuration doesn't match the received response. In the SAML2 response the entity ID is `http://idp.oktadev.com`. The `vm.IdpEntityId` is obviously something else.

**Comment by anthonyrstevens** [comment]
Thank you. Sometimes it's the obvious things that trip you up.
